FROM ubuntu
RUN apt-get update -y
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN apt-get install -y php
RUN apt clean
RUN rm /var/www/html/index.html
COPY ./juggling/* /var/www/html/
EXPOSE 80 
CMD ["apache2ctl", "-D", "FOREGROUND"]
